config/routes.rb
Tasking::Application.routes.draw do
  # authentication
  resources :accounts, only: [:new, :create, :edit, :update] do
    get "activate/:token", as: :activate, on: :collection, action: :activate
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # friendly authentication links
  get "sign_up"  => "accounts#new", as: :sign_up
  get "sign_in"  => "sessions#new", as: :sign_in
  get "sign_out" => "sessions#destroy", as: :sign_out

  # backlog
  resources :stories do
    collection do
      get  :refresh
      post :update_velocity
    end
    member do
      post :update_position
    end
  end

  # sprints
  resources :sprints, only: [:index, :new, :create, :edit, :update] do
    collection do
      get :refresh
    end
  end
  resources :taskable_stories, only: [:update] do
    resources :tasks, only: [:create, :update, :destroy] do
      member do
        post :progress
        post :complete
      end
    end
  end

  # config
  resources :teammates do
    collection do
      get :export
      get :import_form
      get  :refresh
      post :import
    end
  end

  root to: "home#redirect"
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id                :integer          not null, primary key
#  description       :string(255)      not null
#  hours             :decimal(5, 2)    default(1.0), not null
#  status            :string(255)      not null
#  row_order         :integer          not null
#  taskable_story_id :integer          not null
#  team_id           :integer          not null
#  created_at        :datetime
#  updated_at        :datetime
#  teammate_id       :integer
#

class Task < ActiveRecord::Base
  VALID_STATUSES = %w[todo in_progress done]

  include RankedModel
  ranks :row_order, with_same: "taskable_story_id"

  belongs_to :taskable_story, touch: true
  belongs_to :team
  belongs_to :teammate

  validates :description,    presence: true
  validates :hours,          presence: true,
                             numericality: {greater_than_or_equal_to: 0,
                                            allow_nil: true}
  validates :status,         presence: true,
                             inclusion: {in: VALID_STATUSES, allow_nil: true}
  validates :taskable_story, presence: true
  validates :team,           presence: true

  scope :ranked, -> { rank(:row_order) }

  def progress!
    done_index = taskable_story.tasks.pluck("status").find_index { |status| status == "done" }
    done_index = done_index ? (done_index - 1) : :last
    update!(row_order_position: done_index, status: "in_progress")
  end

  def complete!
    update!(status: "done", hours: 0, row_order_position: :last)
  end

  def timed_description=(timed_description)
    matched = timed_description.match(/^(.*)\s+(([\d\.]+)\s*h?)$/)
    self.description, self.hours = matched ? matched.values_at(1, 3) : [timed_description.strip, 0]
  end
end

app/models/task_table.rb
class TaskTable
  KINDS = %w[todo in_progress done]

  attr_reader :sprint, :col_width

  def initialize(sprint, col_width: 145)
    @sprint = sprint
    @col_width = col_width
  end

  def cache_key
    [col_width, KINDS.map { |kind| col_count(kind) }, sprint].join("/")
  end

  def col_count(kind)
    task_count_max[kind] + 1
  end

  def task_count_max
    @task_count_max ||= begin
      tasks = Task
        .select("tasks.taskable_story_id, tasks.status, count(tasks.id) as tasks_count")
        .joins(taskable_story: :sprint)
        .where("taskable_stories.sprint_id = ?", sprint.id)
        .group("tasks.taskable_story_id, tasks.status")
      max_counts = tasks.group_by(&:status).map do |kind, story_tasks|
        [kind, story_tasks.map(&:tasks_count).max]
      end
      Hash.new(0).merge(Hash[max_counts])
    end
  end

  def render_header(kind)
    %Q{<th colspan="#{col_count(kind)}">#{kind.to_s.humanize}</th>}.html_safe
  end

  def each_story_and_tasks(teammate = nil, &block)
    teammate_id = teammate && teammate.id
    sprint.taskable_stories.each do |taskable_story|
      per_status = taskable_story.tasks.ranked.decorate.group_by(&:status)
      tasks = KINDS.each.with_object({}) do |kind, tasks|
        story_tasks = per_status[kind] || []
        count_missing = col_count(kind) - story_tasks.length
        new_task = Task.new(status: kind, teammate_id: teammate_id).decorate
        tasks[kind] = story_tasks + [new_task] * count_missing
      end
      block.call(taskable_story, taskable_story.story.decorate, tasks)
    end
  end

  def table_properties(*column_widths)
    width = column_widths.map { |width| 1 + 8 + width + 8 }.sum
    width += KINDS.map { |kind| 5 + col_width * col_count(kind) }.sum
    {style: "width: #{width}px;"}
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize
  before_action :find_team
  before_action :find_taskable_story
  before_action :find_task, only: [:update, :destroy, :progress, :complete]

  def create
    @task = @taskable_story.tasks.build(task_params.merge(team: @team))
    @task.save!
    publish_change!("create:task")
    respond_with_fresh_task_table
  end

  def update
    @task.update!(task_params)
    publish_change!("update:task")
    respond_with_fresh_task_table
  end

  def destroy
    @task = @taskable_story.tasks.find(params.require(:id))
    @task.destroy
    publish_change!("destroy:task")
    respond_with_fresh_task_table
  end

  def progress
    @task.progress!
    publish_change!("progress:task")
    respond_with_fresh_task_table
  end

  def complete
    @task.complete!
    publish_change!("complete:task")
    respond_with_fresh_task_table
  end

  private

  def find_taskable_story
    @taskable_story = TaskableStory
      .find(params.require(:taskable_story_id))
  end

  def find_task
    @task = @taskable_story.tasks.find(params.require(:id))
  end

  def task_params
    params
      .require(:task)
      .permit(:row_order_position, :timed_description, :description,
              :hours, :status, :teammate_id)
  end

  def refresh_task_table
    @task_table = TaskTable.new(@taskable_story.sprint)
    render :refresh_task_table
  end

  def respond_with_fresh_task_table
    respond_to do |format|
      format.html { redirect_to [:edit, @taskable_story.sprint] }
      format.js   { refresh_task_table }
    end
  end

  def publish_change!(message)
    publish!(message, object: @task, room: "sprints",
      controller: "sprints", id: @taskable_story.sprint_id)
  end
end

app/views/tasks/_task.html.haml
%td.task{style: "width: #{width}px",
         class: task.teammate.decorate.show_color,
         id: dom_id(task),
         data: {task_id: task.id,
                blank: !task.persisted?,
                taskable_story_id: taskable_story.id,
                status: status,
                teammate_id: task.teammate_id,
                position: position}}
  .task-command{style: "width: #{width - 8 * 2 + 1}px"}
    - if task.persisted?
      %button.btn.btn-mini.edit-task(type="button")
        %i.icon-edit
      %button.btn.btn-danger.btn-mini.destroy-task(type="button")
        %i.icon-minus-sign.icon-white
      - case status
      - when "todo"
        %button.btn.btn-primary.btn-mini.progress-task(type="button")
          %i.icon-fast-forward.icon-white
      - when "in_progress"
        %button.btn.btn-success.btn-mini.complete-task(type="button")
          %i.icon-ok.icon-white
      %span.move-task.pull-right
        %i.icon-move.icon-white
    - else
      %button.btn.btn-mini.add-task(type="button")
        %i.icon-plus-sign
  .task-content= task.description
  .task-hours= task.persisted? ? task.duration : ""
  = form_for [taskable_story, task], remote: true, html: {class: "task-form"} do |f|
    = hidden_field_tag "#{f.object_name}[row_order_position]", position
    = f.hidden_field :status
    = f.hidden_field :teammate_id, class: "teammate-id"
    = f.text_area :timed_description, class: "task-input"
  = form_for [taskable_story, task], remote: true, html: {class: "position-task-form"} do |f|
    = f.hidden_field :row_order_position, class: "position"
    = f.hidden_field :status, class: "status"
  = form_tag [taskable_story, task], method: :delete, remote: true, class: "destroy-task-form" do
    %span
  - if task.persisted?
    = form_tag progress_taskable_story_task_path(taskable_story, task), remote: true, class: "progress-task-form" do
      %span
    = form_tag complete_taskable_story_task_path(taskable_story, task), remote: true, class: "complete-task-form" do
      %span

app/views/tasks/_task_table.html.haml
- spec_width = 67
- story_width = 216
%table.table.table-bordered.tasks{task_table.table_properties(43, story_width, 31, spec_width)}
  %thead.table
    %tr
      %th(style="width: 43px") Id
      %th{style: "width: #{story_width}px"} Story
      %th(style="width: 31px") Pts
      %th{style: "width: #{spec_width}px"} Spec
      %th.column-divider(style="width: 0") &nbsp;
      = task_table.render_header("todo")
      %th.column-divider(style="width: 0") &nbsp;
      = task_table.render_header("in_progress")
      %th.column-divider(style="width: 0") &nbsp;
      = task_table.render_header("done")
  %tbody.table
    - task_table.each_story_and_tasks(current_account.teammate) do |taskable_story, story, tasks|
      - cache [task_table, story, taskable_story] do
        - owner = taskable_story.owner.try(:decorate) || NonTeammateDecorator.new
        %tr
          %td= story.id
          %td.story{class: owner.show_color, id: dom_id(taskable_story)}
            .story-command(style="width: 28px")
              %button.btn.btn-mini.edit-story(type="button")
                %i.icon-edit
            .story-content= story.description
            = form_for taskable_story, html: {class: "story-form"}, remote: true do |f|
              = f.hidden_field :owner_id, id: nil
              = f.text_area :description, id: nil, class: "story-input"
          %td= story.points
          %td
            .width-container{style: "width: #{spec_width}px"}= story.link_to_spec
          - position = 0
          - %w[todo in_progress done].each do |kind|
            %td.column-divider &nbsp;
            - tasks[kind].each do |task|
              - cache [task, position, kind, taskable_story, task_table.col_width] do
                = render "tasks/task",
                          task: task,
                          position: position,
                          status: kind,
                          taskable_story: taskable_story,
                          width: task_table.col_width
              - position = 1

app/views/tasks/create.js.erb
App.pageUpdateManager.refreshMain({
  controllerName: "sprints",
  replace: [
    "#task-table-wrapper",
    "<%= escape_javascript render('task_table', task_table: @task_table) %>"
  ],
  highlight: "#<%= dom_id @task %>"
});

app/views/tasks/refresh_task_table.js.erb
App.pageUpdateManager.refreshMain({
  controllerName: "sprints",
  replace: [
    "#task-table-wrapper",
    "<%= escape_javascript render('task_table', task_table: @task_table) %>"
  ],
  highlight: "#<%= dom_id @task %>"
});