config/routes.rb
Tasking::Application.routes.draw do
  # authentication
  resources :accounts, only: [:new, :create, :edit, :update] do
    get "activate/:token", as: :activate, on: :collection, action: :activate
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # friendly authentication links
  get "sign_up"  => "accounts#new", as: :sign_up
  get "sign_in"  => "sessions#new", as: :sign_in
  get "sign_out" => "sessions#destroy", as: :sign_out

  # backlog
  resources :stories do
    collection do
      get  :refresh
      post :update_velocity
    end
    member do
      post :update_position
    end
  end

  # sprints
  resources :sprints, only: [:index, :new, :create, :edit, :update] do
    collection do
      get :refresh
    end
  end
  resources :taskable_stories, only: [:update] do
    resources :tasks, only: [:create, :update, :destroy] do
      member do
        post :progress
        post :complete
      end
    end
  end

  # config
  resources :teammates do
    collection do
      get :export
      get :import_form
      get  :refresh
      post :import
    end
  end

  root to: "home#redirect"
end

app/models/teammate.rb
# == Schema Information
#
# Table name: teammates
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  roles      :string(255)      default([])
#  account_id :integer
#  created_at :datetime
#  updated_at :datetime
#  team_id    :integer          not null
#  color      :string(255)      not null
#  initials   :string(255)      not null
#

class Teammate < ActiveRecord::Base
  ROLES  = %w[teammate tech_lead product_manager]
  COLORS = %w[baby-blue dark-beige dark-blue dark-green dark-purple light-green
              old-pink orange pink black purple red salmon yellow]

  belongs_to :team
  belongs_to :account

  validates :name,     presence: true, uniqueness: {case_sensitive: false}
  validates :initials, presence: true, uniqueness: {case_sensitive: false}
  validates :color,    presence: true,
                       inclusion: {in: COLORS, allow_nil: true}
  validates :team,     presence: true

  before_validation :set_initials_if_missing

  scope :with_role, -> (role) { where("roles @> '{#{role.inspect}}'") }
  scope :tech_leads, -> { with_role("tech_lead").order("name") }
  scope :product_managers, -> { with_role("product_manager").order("name") }

  delegate :email, to: :account, prefix: true, allow_nil: true

  private

  def set_initials_if_missing
    return if initials.present? || name.nil?
    names = name.split(/\s/)
    self.initials = case names.length
                    when 0
                      ""
                    when 1
                      names.first[0..2].upcase
                    else
                      names.map(&:first).join.upcase
                    end
  end
end

app/controllers/teammates_controller.rb
class TeammatesController < ApplicationController
  before_action :authorize
  before_action :find_team
  before_action :find_teammate, only: [:edit, :update, :destroy]

  def index
    authorize! :read, Teammate
    setup_to_render_main
    register_to_pubsub!
  end

  def new
    authorize! :create, Teammate
    @teammate = TeammateForm.new
    setup_to_render_main
    register_to_pubsub!
  end

  def create
    authorize! :create, Teammate
    @teammate = TeammateForm.new(teammate_params)
    respond_to do |format|
      if @teammate.submit(scope: @team)
        notice = "New teammate was created."
        publish!("create", object: @teammate)
        format.html { redirect_to teammates_url, notice: notice }
        format.js   { setup_to_render_main; flash.now[:notice] = notice }
      else
        format.html { setup_to_render_main(true); render :new }
        format.js   { render :create_error }
      end
    end
  end

  def edit
    authorize! :update, @teammate
    @teammate = TeammateForm.from_teammate(@teammate)
    setup_to_render_main
    register_to_pubsub!
  end

  def update
    authorize! :update, @teammate
    @teammate = TeammateForm.new(teammate_params.merge(teammate_id: @teammate.id))
    respond_to do |format|
      if @teammate.submit(scope: @team)
        notice = "Teammate #{@teammate.name.inspect} was updated."
        publish!("update", object: @teammate)
        format.html { redirect_to teammates_url, notice: notice }
        format.js   { setup_to_render_main; flash.now[:notice] = notice; render :create }
      else
        format.html { setup_to_render_main(true); render :edit }
        format.js   { render :update_error }
      end
    end
  end

  def destroy
    authorize! :destroy, @teammate
    Teammate.transaction do
      @teammate.account.destroy if @teammate.account
      @teammate.destroy
    end
    warning = "Teammate #{@teammate.name.inspect} was deleted."
    publish!("destroy", object: @teammate)
    respond_to do |format|
      format.html { redirect_to teammates_url, warning: warning }
      format.js   { setup_to_render_main; flash.now[:warning] = warning }
    end
  end

  def export
    authorize! :read, Teammate
    respond_to do |format|
      format.csv {
        send_data(exporter.teammates(:csv, team: @team),
          filename: "teammates-#{Time.zone.today.to_s(:db)}.csv")
      }
    end
  end

  def import_form
    authorize! :create, Teammate
    setup_to_render_main
    @required_columns = DataExchange::ImportTeammatesCsv::MANDATORY
    @optional_columns = DataExchange::ExportTeammatesCsv::HEADER - @required_columns
  end

  def import
    authorize! :create, Teammate
    result = importer.teammates(csv: import_params.read, team: @team)
    publish!("import:success")
    flash[:info] = "Import was successful: #{result[:added]} added, #{result[:updated]} updated."
  rescue StandardError => error
    flash[:error] = "Import failed: #{error.message}"
  ensure
    redirect_to teammates_url
  end

  def refresh
    authorize! :read, Teammate
    setup_to_render_main
    render layout: false
  end

  private

  def setup_to_render_main(reload = false)
    @team.teammates.reload if reload
    @teammates = @team.teammates.decorate
  end

  def teammate_params
    secured = params
      .require(:teammate)
      .permit(:name, :account_id, :initials, :color, :roles, :email, roles: [])
    secured[:roles] ||= []
    secured[:roles] = secured[:roles].split(",") if secured[:roles].is_a?(String)
    secured[:roles].reject!(&:blank?)
    secured
  end

  def import_params
    params.require(:file)
  end

  def find_teammate
    @teammate = @team.teammates.find(params.require(:id))
  end

  def exporter
    DataExchangeService.new.export
  end

  def importer
    DataExchangeService.new.import
  end
end

app/views/teammates/_edit_button.html.haml
.command.btn-group{:"data-content" => target.to_json, :"data-position" => position}
  = link_to edit_teammate_path(target), class: "btn btn-mini" do
    %i.icon-pencil
  %button.btn.btn-mini.dropdown-toggle(data-toggle="dropdown")
    %span.caret
  %ul.dropdown-menu
    %li
      = link_to edit_teammate_path(target) do
        %i.icon-pencil
        Edit Teammate
    %li.divider
    %li
      = link_to teammate_path(target), method: :delete, data: {remote: true} do
        %i.icon-minus-sign
        Delete Teammate

app/views/teammates/_editor.html.haml
#editor.modal.hide{tabindex: -1, role: "dialog", class: teammate.errors.empty? ? "fade" : "" }
  = render "teammate_form", teammate: teammate, title: title

app/views/teammates/_main.html.haml
- page_title "Teammates"
- page_description do
  = render "page_description"

- content_for :javascript do
  = javascript_tag "App.teammates.setup();"

= render "teammates_list", teammates: teammates

app/views/teammates/_page_description.html.haml
%p Manage the list of teammates to use.
%p
  = link_to new_teammate_path, class: "btn btn-primary" do
    %i.icon-plus.icon-white
    Teammate
  = link_to import_form_teammates_path, class: "btn btn-success" do
    %i.icon-upload.icon-white
    Import
    %i.icon-arrow-left.icon-white
    CSV
  = link_to export_teammates_path(format: :csv), class: "btn btn-info", data: {no_turbolink: true} do
    %i.icon-download.icon-white
    Export
    %i.icon-arrow-right.icon-white
    CSV

app/views/teammates/_teammate_form.html.haml
= simple_form_for teammate,
    url: teammate.path,
    method: teammate.method,
    html: {class: "form-horizontal"},
    defaults: {input_html: {class: "input-xlarge"}},
    data: {remote: true} do |f|
  .modal-header
    = link_to "x", teammates_path, class: "close"
    %h3.title= title
  .modal-body
    - if teammate.errors.present?
      .alert.alert-error
        %button.close(type="button" data-dismiss="alert") &times;
        %strong
          Can't
          = teammate.persisted? ? "update" : "create"
          teammate.
        Please fix the errors below.
    = f.input :name
    = f.input :roles, as: :check_boxes, collection: Teammate::ROLES
    = f.input :email, as: :email, disabled: teammate.email.present?
    = f.input :color, as: :select, collection: Teammate::COLORS
    = f.input :initials
  .modal-footer
    = link_to "Cancel", teammates_path, class: "btn cancel"
    = f.button :submit, class: "btn-primary"

app/views/teammates/_teammates_list.html.haml
- cache teammates do
  - if teammates.empty?
    %table.table.table-bordered
      %tbody.table
        %tr
          %td
            %p
              There are no teammates yet.
  - else
    %table.table.table-stripped.table-hover.hidden-commands
      %thead.table
        %tr
          %th Name
          %th Roles
          %th Color
          %th Account
          %th Updated
      %tbody.table
        - teammates.each.with_index do |teammate, index|
          - cache [teammate, index] do
            %tr{id: dom_id(teammate)}
              %td<
                = render "edit_button", target: teammate, position: index
                = teammate.name
                (
                = teammate.initials
                )
              %td= teammate.role_labels
              %td{teammate.show_color_class}= teammate.color
              %td= teammate.account_email
              %td= teammate.updated_at

app/views/teammates/destroy.js.erb
App.pageUpdateManager.refreshMain({
  controllerName: "<%= controller_name %>",
  replace: [
    "#main",
    "<%= escape_javascript render('teammates_list', teammates: @teammates) %>"
  ],
  prepend: [
    "#page-description",
    "<%= escape_javascript flash_messages %>"
  ],
  newUrl: "<%= teammates_url %>"
});

app/views/teammates/edit.html.haml
= render "main", teammates: @teammates
- cache @teammate do
  = render "editor", teammate: @teammate, title: "Edit teammate #{@teammate.name.inspect}"

app/views/teammates/import_form.html.haml
= render "main", teammates: @teammates
- cache "v1" do
  #editor.modal.fade.hide{tabindex: -1, role: "dialog"}
    = form_tag import_teammates_path, multipart: true, class: "form-horizontal" do
      .modal-header
        = link_to "x", teammates_path, class: "close"
        %h3.title Import Teammates
      .modal-body
        %p
          Please select the CSV file to import and click on
          %em Upload File.
        %p
          The file must contain a header with at least those required columns:
          - @required_columns.each do |name|
            %code= name
        %p
          Those columns are optional:
          - @optional_columns.each do |name|
            %code= name
        %br

        .fileupload.fileupload-new(data-provides="fileupload")
          .input-append
            .uneditable-input.span3
              %i.icon-file.fileupload-exists
              %span.fileupload-preview
            %span.btn.btn-file
              %span.fileupload-new Select File
              %span.fileupload-exists Change
              = file_field_tag :file, accept: "text/csv"
            %a.btn.fileupload-exists(href data-dismiss="fileupload") Remove
      .modal-footer
        = link_to "Cancel", teammates_path, class: "btn cancel"
        = submit_tag "Upload File", class: "btn-primary"

app/views/teammates/new.html.haml
= render "main", teammates: @teammates
- cache @teammate do
  = render "editor", teammate: @teammate, title: "New teammate"