config/routes.rb
Tasking::Application.routes.draw do
  # authentication
  resources :accounts, only: [:new, :create, :edit, :update] do
    get "activate/:token", as: :activate, on: :collection, action: :activate
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # friendly authentication links
  get "sign_up"  => "accounts#new", as: :sign_up
  get "sign_in"  => "sessions#new", as: :sign_in
  get "sign_out" => "sessions#destroy", as: :sign_out

  # backlog
  resources :stories do
    collection do
      get  :refresh
      post :update_velocity
    end
    member do
      post :update_position
    end
  end

  # sprints
  resources :sprints, only: [:index, :new, :create, :edit, :update] do
    collection do
      get :refresh
    end
  end
  resources :taskable_stories, only: [:update] do
    resources :tasks, only: [:create, :update, :destroy] do
      member do
        post :progress
        post :complete
      end
    end
  end

  # config
  resources :teammates do
    collection do
      get :export
      get :import_form
      get  :refresh
      post :import
    end
  end

  root to: "home#redirect"
end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id                 :integer          not null, primary key
#  description        :text             default("As a role\nI can do something\nso I get a benefit"), not null
#  points             :integer          default(3), not null
#  row_order          :integer          not null
#  tech_lead_id       :integer
#  product_manager_id :integer
#  business_driver    :string(255)
#  spec_link          :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  team_id            :integer          not null
#

class Story < ActiveRecord::Base
  VALID_POINTS = [0, 1, 2, 3, 5, 8, 13, 21]

  include RankedModel
  ranks :row_order, with_same: "team_id"

  belongs_to :team
  belongs_to :tech_lead, class_name: "Teammate"
  belongs_to :product_manager, class_name: "Teammate"
  has_many   :taskable_stories, dependent: :destroy

  validates :points,      presence: true, inclusion: VALID_POINTS
  validates :description, presence: true
  validates :team,        presence: true

  delegate :name, to: :tech_lead, prefix: true, allow_nil: true
  delegate :name, to: :product_manager, prefix: true, allow_nil: true

  scope :ranked, -> { rank(:row_order) }
  scope :backlogged, -> {
    joins("LEFT JOIN taskable_stories ON (taskable_stories.story_id = stories.id)")
    .where("taskable_stories.story_id IS NULL")
  }
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authorize
  before_action :find_team
  before_action :find_story, only: [:edit, :update, :update_position, :destroy]

  def index
    setup_to_render_main
    register_to_pubsub!
  end

  def new
    @story = Story.new(row_order_position: params[:row_order_position])
    setup_to_render_main
    register_to_pubsub!
  end

  def create
    @story = @team.stories.build(story_params)
    respond_to do |format|
      if @story.save
        publish!("create:success", object: @story)
        notice = "New story was created."
        format.html { redirect_to stories_url, notice: notice }
        format.js   { setup_to_render_main; flash.now[:notice] = notice }
      else
        format.html { setup_to_render_main; render :new }
        format.js   { render :create_error }
      end
    end
  end

  def edit
    setup_to_render_main
    register_to_pubsub!
  end

  def update
    respond_to do |format|
      if @story.update(story_params)
        publish!("update:success", object: @story)
        format.html { redirect_to stories_url }
        format.js   { setup_to_render_main }
      else
        format.html { setup_to_render_main; render :edit }
        format.js   { render :update_error }
      end
    end
  end

  def update_position
    @story.update(row_order_position: params.require(:position))
    publish!("update_position:success", object: @story)
    respond_to do |format|
      format.html { redirect_to stories_url }
      format.js   { setup_to_render_main; render :update }
    end
  end

  def destroy
    @story.destroy
    warning = "Story ##{@story.id} was deleted."
    publish!("destroy", object: @story)
    respond_to do |format|
      format.html { redirect_to stories_url, warning: warning }
      format.js   { setup_to_render_main; flash.now[:warning] = warning }
    end
  end

  def update_velocity
    @team.update(projected_velocity: params.require(:velocity))
    publish!("update_velocity")
    respond_to do |format|
      format.html { redirect_to stories_url }
      format.js   { setup_to_render_main }
    end
  end

  def refresh
    setup_to_render_main
    render layout: false
  end

  private

  def setup_to_render_main
    @stories = @team.stories.ranked.backlogged.decorate
    @velocity = VelocityService.new(@team.projected_velocity, @stories)
  end

  def story_params
    extracted = params
      .require(:story)
      .permit(:description, :points, :tech_lead_id, :product_manager_id,
              :business_driver, :spec_link, :row_order_position)
    extracted.delete(:row_order_position) if extracted[:row_order_position].blank?
    extracted
  end

  def find_story
    @story = @team.stories.find(params.require(:id))
  end
end

app/views/stories/_edit_button.html.haml
.command.btn-group{:"data-content" => target.to_json, :"data-position" => position}
  = link_to edit_story_path(target), class: "btn btn-mini" do
    %i.icon-pencil
  %button.btn.btn-mini.dropdown-toggle(data-toggle="dropdown")
    %span.caret
  %ul.dropdown-menu
    %li
      = link_to edit_story_path(target) do
        %i.icon-pencil
        Edit Story
    %li
      = link_to new_story_path(row_order_position: position) do
        %i.icon-arrow-up
        Add New Story Above
    %li
      = link_to new_story_path(row_order_position: position + 1) do
        %i.icon-arrow-down
        Add New Story Below
    %li.divider
    %li
      = link_to update_position_story_path(target, position: :first), method: :post, data: {remote: true} do
        %i.icon-circle-arrow-up
        Move to TOP
    %li
      = link_to update_position_story_path(target, position: :middle), method: :post, data: {remote: true} do
        %i.icon-circle-arrow-right
        Move to MIDDLE
    %li
      = link_to update_position_story_path(target, position: :last), method: :post, data: {remote: true} do
        %i.icon-circle-arrow-down
        Move to BOTTOM
    %li.divider
    %li
      = link_to target, method: :delete, data: {remote: true} do
        %i.icon-minus-sign
        Delete Story

app/views/stories/_editor.html.haml
#editor.modal.hide{tabindex: -1, role: "dialog", class: story.errors.empty? ? "fade" : "" }
  = render "story_form", story: story, title: title

app/views/stories/_list_summary.html.haml
%table.table.table-bordered.table-striped
  %colgroup
    %col(width="10%")
    %col(width="80%")
    %col(width="10%")
  %thead.table
    %tr
      %th Id
      %th User story
      %th Points
  %tbody.table
    - stories.each do |story|
      %tr
        %td= story.id
        %td= story.description
        %td= story.badged_points

app/views/stories/_main.html.haml
- page_title "Product Backlog", size: "span5"
- page_description size: "span7"

- content_for :javascript do
  = javascript_tag "App.stories.setup();"

= render "stories", stories: stories, velocity: velocity

app/views/stories/_stories.html.haml
- cache [stories, velocity] do
  %p The ordered list of "requirements" that is maintained for your product.

  - if stories.empty?
    %table.table.table-bordered
      %tbody.table
        %tr
          %td
            %p
              There are no stories in the backlog yet.
              &nbsp;
              = link_to "Create first story", new_story_path, class: "btn btn-primary"
  - else
    %p
      You can mouse over a story to reveal a story management button or &nbsp;
      = link_to "Create a story", new_story_path, class: "btn btn-primary"
    %br
    %table.table.table-hover.hidden-commands
      %colgroup
        %col(width="30px")
        %col(span="2" width="75px")
        %col(width="60px")
        %col(width="300px")
        %col(width="30px")
        %col(width="150px")
      %thead.table
        %tr
          %th Id
          %th Tech lead
          %th PM
          %th Driver
          %th User story
          %th Points
          %th Spec
      %tbody#stories.table
        - stories.each.with_index do |story, index|
          = render "velocity_bar", velocity: velocity if index == 0 && velocity.index == 0
          - cache story do
            = render "story_row", story: story, index: index
          = render "velocity_bar", velocity: velocity if velocity.index == index + 1

app/views/stories/_story_form.html.haml
= simple_form_for story,
    html: {class: "form-horizontal"},
    defaults: {input_html: {class: "input-xlarge"}},
    data: {remote: true} do |f|
  = f.hidden_field :row_order_position
  .modal-header
    = link_to "x", stories_path, class: "close"
    %h3.title= title
  .modal-body
    - if story.errors.present?
      .alert.alert-error
        %button.close(type="button" data-dismiss="alert") &times;
        %strong
          Can't
          = story.persisted? ? "update" : "create"
          story.
        Please fix the errors below.
    = f.input :description, input_html: {rows: 5}
    .control-group.radio_buttons.required
      = f.label :points
      .controls
        = f.hidden_field :points
        .point-selector.btn-group(data-toggle="buttons-radio")
          - Story::VALID_POINTS.each do |value|
            %button.btn{type: "button",
                        class: value == story.points ? "active" : "",
                        :"data-value" => value}= value
    = f.association :tech_lead, collection: @team.teammates.tech_leads
    = f.association :product_manager, collection: @team.teammates.product_managers
    = f.input :business_driver
    = f.input :spec_link, as: :url
  .modal-footer
    = link_to "Cancel", stories_path, class: "btn cancel"
    = f.button :submit, class: "btn-primary"

app/views/stories/_story_row.html.haml
%tr.story-row{:"data-id" => story.id,
              :"data-position" => index,
              :"data-position-url" => update_position_story_path(story),
              :id => dom_id(story)}
  %td
    %div(style="display: none")
      = form_tag update_position_story_path(story), method: :post, data: {remote: true} do
        = hidden_field_tag :position, nil, id: nil
    = render "edit_button", target: story, position: index
    = story.id
  %td= story.tech_lead_name
  %td= story.product_manager_name
  %td= story.business_driver
  %td= story.description
  %td= story.badged_points
  %td= story.link_to_spec

app/views/stories/_velocity_bar.html.haml
%tr.success
  %td &nbsp;
  %td(colspan="4")
    %p.text-center
      %strong This is where we wish the line to be... &nbsp;
      - if velocity.sum > 0
        = link_to "New Sprint",
          new_sprint_path(sprint: {story_ids: velocity.included_story_ids}),
          class: "btn btn-success",
          id: "btn-new-sprint"
  %td
    %strong= velocity.sum
  %td
    = form_tag update_velocity_stories_path, class: "form-inline-row", data: {remote: true} do
      = text_field_tag :velocity, velocity.value,
                                  min: 1,
                                  class: "input-micro",
                                  autocomplete: "off"

app/views/stories/create.js.erb
App.pageUpdateManager.refreshMain({
  controllerName: "<%= controller_name %>",
  modal: "#editor",
  replace: [
    "#main",
    "<%= escape_javascript render('stories', stories: @stories, velocity: @velocity) %>"
  ],
  highlight: "#<%= dom_id @story %>",
  prepend: [
    "#page-description",
    "<%= escape_javascript flash_messages %>"
  ],
  newUrl: "<%= stories_url %>"
});

app/views/stories/destroy.js.erb
App.pageUpdateManager.refreshMain({
  controllerName: "<%= controller_name %>",
  replace: [
    "#main",
    "<%= escape_javascript render('stories', stories: @stories, velocity: @velocity) %>"
  ],
  prepend: [
    "#page-description",
    "<%= escape_javascript flash_messages %>"
  ],
  newUrl: "<%= stories_url %>"
});

app/views/stories/edit.html.haml
= render "main", stories: @stories, velocity: @velocity
- cache @story do
  = render "editor", story: @story, title: "Edit story ##{@story.id}"

app/views/stories/index.html.haml
= render "main", stories: @stories, velocity: @velocity

app/views/stories/new.html.haml
= render "main", stories: @stories, velocity: @velocity
- cache @story do
  = render "editor", story: @story, title: "New Story"

app/views/stories/update_velocity.js.erb
App.pageUpdateManager.refreshMain({
  controllerName: "<%= controller_name %>",
  replace: [
    "#main",
    "<%= escape_javascript render('stories', stories: @stories, velocity: @velocity) %>"
  ],
  newUrl: "<%= stories_url %>"
});