config/routes.rb
Tasking::Application.routes.draw do
  # authentication
  resources :accounts, only: [:new, :create, :edit, :update] do
    get "activate/:token", as: :activate, on: :collection, action: :activate
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # friendly authentication links
  get "sign_up"  => "accounts#new", as: :sign_up
  get "sign_in"  => "sessions#new", as: :sign_in
  get "sign_out" => "sessions#destroy", as: :sign_out

  # backlog
  resources :stories do
    collection do
      get  :refresh
      post :update_velocity
    end
    member do
      post :update_position
    end
  end

  # sprints
  resources :sprints, only: [:index, :new, :create, :edit, :update] do
    collection do
      get :refresh
    end
  end
  resources :taskable_stories, only: [:update] do
    resources :tasks, only: [:create, :update, :destroy] do
      member do
        post :progress
        post :complete
      end
    end
  end

  # config
  resources :teammates do
    collection do
      get :export
      get :import_form
      get  :refresh
      post :import
    end
  end

  root to: "home#redirect"
end

app/views/layouts/_dropdown_menu.html.haml
- active = nil unless defined?(active)
%li.dropdown{:class => controller_name == active ? "active" : ""}
  %a.dropdown-toggle(href data-toggle="dropdown")
    = label
    %b.caret
  %ul.dropdown-menu
    - entries.each do |entry|
      - if entry[:divider]
        %li.divider
      - else
        = render "layouts/nav_link", entry

app/views/layouts/_dropdown_nav_links.html.haml
- active = nil unless defined?(active)
%li.dropdown{:class => controller_name == active ? "active" : ""}
  %a.dropdown-toggle(href data-toggle="dropdown")
    = label
    %b.caret
  %ul.dropdown-menu= yield

app/views/layouts/_nav_link.html.haml
%li{class: current_page?(url) ? "active" : ""}= link_to label, url

app/views/layouts/_navigation_bar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      - brand_path = current_account ? stories_path : root_path
      = link_to "Tasking", brand_path, class: "brand"
      .nav-collapse.collapse
        %ul.nav
          %li.divider-vertical
          - if current_account
            = render "layouts/nav_link", label: "Backlog", url: stories_path
            %li.divider-vertical
            = render "layouts/dropdown_menu", label: "Sprints", active: "sprints",
              entries: [{label: "Current",  url: edit_sprint_path(:current)},
                        {divider: true},
                        {label: "Upcoming", url: edit_sprint_path(:next)},
                        {label: "Last", url: edit_sprint_path(:last)},
                        {divider: true},
                        {label: "All sprints",  url: sprints_path}]
            - if can? :update, Teammate
              %li.divider-vertical
              = render "layouts/nav_link", label: "Teammates", url: teammates_path
            %li.divider-vertical
            = render "layouts/dropdown_menu", label: current_account.email,
              entries: [{label: "My Account", url: edit_account_path(current_account)},
                        {divider: true},
                        {label: "Sign Out", url: sign_out_path}]
          - else
            = render "layouts/nav_link", label: "Sign Up", url: sign_up_path
            %li.divider-vertical
            = render "layouts/nav_link", label: "Sign In", url: sign_in_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body#body.preserve-scroll{data: @config || {}}
    = render "layouts/navigation_bar"
    %header.title
      .summary-bar.container
        .row
          %div{page_width(:title)}
            %h1= page_title
          #page-description{page_width(:description)}
            = flash_messages
            = yield(:page_description)

    .main-content{page_container}
      %br
      #main
        = yield
        = yield :javascript